site_name: Hola Mundo PySide6
theme:
  name: material
 
nav:
  - Inicio: index.md
  - About: about.md
  - Descarga en PDF: pdf.md
 
plugins:
  - search
  - with-pdf:
      output_path: C:\Users\ANTIA\OneDrive - NT FOR LEARNING SL\Escritorio\DAM\SEGUNDO CURSO\DESARROLLO DE INTERFACES\Pypi\docs\documentacion.pdf
      cover_title: "Hola Mundo PySide6"
      cover_subtitle: "Documentación del proyecto"
      toc_title: "Índice"